name: fake_store_repository
description: "A Dart repository for our domain logic"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  fake_store_api:
    path: ../fake_store_api

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4
































